### ISSUE TITLE
error log reading 'getBoundingClientRect'

### ISSUE THREAD

**Issue by ruben-with-b** [TahaSh/aat#1]
Hi, thanks for this great lib!

I have a scroll implementation and this error in my log, once I scroll

`Uncaught TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at get _elRectRelativeToContainer (aat.min.js:1:2081)
    at d._calculatePercentageY (aat.min.js:1:2380)
    at d._onScroll (aat.min.js:1:2726)
    at d.onScroll (aat.min.js:1:621)
    at custom.js:174:5
    at Array.forEach (<anonymous>)
    at custom.js:160:19`

This is my setup in js:
`const cardsContainer = document.querySelector(".cards .elementor-widget-wrap");
const cards = document.querySelectorAll(".fkf_testimonal_card");
const headlineContainer = document.querySelector(".fkf_stack_right .elementor-shortcode");

cardsContainer.style.setProperty("--cards-count", cards.length);
cardsContainer.style.setProperty("--card-height", `${cards[0].clientHeight}px`);

headlineContainer.style.height = cardsContainer.offsetHeight + 'px';

Array.from(cards).forEach((card, index) => {
	const offsetTop = index * 8;
	
	if (index === cards.length) {
		return;
	}
	
	const toScale = -(index - 10) * -0.75;
	const nextCard = cards[index + 1];
	const cardInner = card.querySelector(".fkf_testimonal_card .elementor-widget-container");
	
	ScrollObserver.Element(nextCard, {
		offsetTop,
		offsetBottom: window.innerHeight - card.clientHeight
	}).onScroll(({ percentageY }) => {
		cardInner.style.transform = `rotate(${valueAtPercentage({
			from: 0,
			to: toScale,
			percentage: percentageY
		})}deg)`;
	});
});`

**Comment by ruben-with-b** [comment]
Any news here :)

**Comment by TahaSh** [comment]
@ruben-with-b sorry I took a while to get back to you! To fix this, you need to make sure that the next card you access is within limits. So, you need to update the check to ensure that the current card in the loop is not the last card.

So, update `if (index === cards.length)` to `if (index === cards.length - 1)` in this code:

```js
Array.from(cards).forEach((card, index) => {
  const offsetTop = index * 8

  if (index === cards.length) {
    return
  }
  // ...
```

So it becomes this:

```js
Array.from(cards).forEach((card, index) => {
  const offsetTop = index * 8

  if (index === cards.length - 1) {
    return
  }
  // ...
```
Let me know if you have any questions :)

**Comment by ruben-with-b** [comment]
Perfect, that was the issue. Thanks a lot!!

**Comment by TahaSh** [comment]
Glad to hear that :)
